import { Button, Link } from '@chakra-ui/react';
import { LayoutDefault } from '@components/LayoutDefault/LayoutDefault';
import { PokemonList } from '@components/PokemonList/PokemonList';
import { PokemonListItem } from '@components/PokemonListItem/PokemonListItem';
import { useQueryPokemon } from '@hooks/index';
import { Pokemon } from '@typedef/pokemon';
import { capitalizeFirstLetter } from '@utils/uppercase';
import Head from 'next/head'
import NextLink from 'next/link';
import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const pokemons = useQueryPokemon()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonList
        isLoading={pokemons.isLoading}
        isError={pokemons.isError}
      >
        {
          pokemons.data?.pages.map((group) =>
            group?.results.map((pokemon: Pokemon) => <div key={pokemon.name}>
              <PokemonListItem>
                <NextLink href={`/pokemon/${pokemon.name}`} key={pokemon.name} passHref>
                  <Link width="100%" height="100%" textAlign="center" _hover={{}}>
                    {capitalizeFirstLetter(pokemon.name)}
                  </Link>
                </NextLink>
              </PokemonListItem>
            </div>)
          )
        }
        <Button
          onClick={() => pokemons.fetchNextPage()}
          disabled={!pokemons.hasNextPage || pokemons.isFetchingNextPage}
        >
          {pokemons.isFetchingNextPage
            ? "Loading more..."
            : pokemons.hasNextPage
              ? "Load More"
              : "Nothing more to load"}
        </Button>
      </PokemonList>
    </>
  )
}

Home.getLayout = page => <LayoutDefault>{page}</LayoutDefault>;

export default Home